spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enable-spring-el-compiler: false
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    #view-names: ''
server:
  error:
    whitelabel:
      enabled: true #esta propiedad muestra por defecto la vista de spring