spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enable-spring-el-compiler: false
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    view-names: ''
