# ===============================
# = THYMELEAF
# ===============================
spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enable-spring-el-compiler: false
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    #view-names: ''
    
# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
  datasource:
    url: jdbc:mysql://localhost:3306/mydb #mydb es el nombre de la base de datos
    username: root
    password: root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# Keep the connection alive if idle for a long time (needed in production)
#spring.datasource.testWhileIdle=true
#spring.datasource.validationQuery=SELECT 1
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
  jpa:
    show-sql: true  #Para mostrar en el LOG las diferentes querys que se ejecuten
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update  #Comprueba que las Entities se corresponden con las tablas, si no
                        #se corresponden, va a actualziar las tablas

# Naming strategy --> Es la forma (dialecto) que va a usar al momento de hacer las consultas
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
# Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Para visualizar la vista de spring cuando se produce un error (enabled=true)
# ===============================
server:
  error:
    whitelabel:
      enabled: true #esta propiedad muestra por defecto la vista de spring